export type TranslatorLanguage = {
  code: string;
  name: string;
  localName?: string;
  direction: "ltr" | "rtl";
};

export const translatorDetectLanguage: TranslatorLanguage = {
  code: "detect",
  name: "Detect Language",
  direction: "ltr",
};

export const translatorLanguages: TranslatorLanguage[] = [
  { code: "ab", name: "Abkhaz", localName: "Аҧсуа", direction: "ltr" },
  { code: "ace", name: "Acehnese", localName: "بهسا اچيه", direction: "ltr" },
  { code: "ach", name: "Acholi", localName: "Lwo", direction: "ltr" },
  { code: "aa", name: "Afar", localName: "Afaraf", direction: "ltr" },
  { code: "af", name: "Afrikaans", direction: "ltr" },
  { code: "sq", name: "Albanian", localName: "Shqip", direction: "ltr" },
  { code: "alz", name: "Alur", direction: "ltr" },
  { code: "am", name: "Amharic", localName: "አማርኛ", direction: "ltr" },
  { code: "ar", name: "Arabic", localName: "العربية", direction: "rtl" },
  { code: "hy", name: "Armenian", localName: "Հայերեն", direction: "ltr" },
  { code: "as", name: "Assamese", localName: "অসমীয়া", direction: "ltr" },
  { code: "av", name: "Avar", localName: "Авар", direction: "ltr" },
  { code: "awa", name: "Awadhi", localName: "अवधी", direction: "ltr" },
  { code: "ay", name: "Aymara", localName: "Aymar aru", direction: "ltr" },
  {
    code: "az",
    name: "Azerbaijani",
    localName: "Azərbaycanca",
    direction: "ltr",
  },
  { code: "ban", name: "Balinese", localName: "ᬪᬵᬱᬩᬮᬶ", direction: "ltr" },
  { code: "bal", name: "Baluchi", localName: "بلوچی", direction: "rtl" },
  { code: "bm", name: "Bambara", localName: "Bamanankan", direction: "ltr" },
  { code: "bci", name: "Baoulé", direction: "ltr" },
  { code: "ba", name: "Bashkir", localName: "Башҡорт", direction: "ltr" },
  { code: "eu", name: "Basque", localName: "Euskara", direction: "ltr" },
  { code: "btk", name: "Batak Karo", direction: "ltr" },
  { code: "bts", name: "Batak Simalungun", direction: "ltr" },
  { code: "bbc", name: "Batak Toba", direction: "ltr" },
  { code: "be", name: "Belarusian", localName: "Беларуская", direction: "ltr" },
  { code: "bem", name: "Bemba", localName: "Ichibemba", direction: "ltr" },
  { code: "bn", name: "Bengali", localName: "বাংলা", direction: "ltr" },
  { code: "bew", name: "Betawi", direction: "ltr" },
  { code: "bho", name: "Bhojpuri", localName: "भोजपुरी", direction: "ltr" },
  { code: "bik", name: "Bikol", direction: "ltr" },
  { code: "bs", name: "Bosnian", localName: "Bosanski", direction: "ltr" },
  { code: "br", name: "Breton", localName: "Brezhoneg", direction: "ltr" },
  { code: "bg", name: "Bulgarian", localName: "Български", direction: "ltr" },
  { code: "bua", name: "Buryat", localName: "Буряад", direction: "ltr" },
  { code: "yue", name: "Cantonese", localName: "廣東話", direction: "ltr" },
  { code: "ca", name: "Catalan", localName: "Català", direction: "ltr" },
  { code: "ceb", name: "Cebuano", localName: "Binisaya", direction: "ltr" },
  { code: "ch", name: "Chamorro", localName: "Chamoru", direction: "ltr" },
  { code: "ce", name: "Chechen", localName: "Нохчийн", direction: "ltr" },
  { code: "ny", name: "Chichewa", localName: "Chicheŵa", direction: "ltr" },
  {
    code: "zh-CN",
    name: "Chinese (Simplified)",
    localName: "简体中文",
    direction: "ltr",
  },
  {
    code: "zh-TW",
    name: "Chinese (Traditional)",
    localName: "繁體中文",
    direction: "ltr",
  },
  { code: "chk", name: "Chuukese", direction: "ltr" },
  { code: "cv", name: "Chuvash", localName: "Чӑваш", direction: "ltr" },
  { code: "co", name: "Corsican", localName: "Corsu", direction: "ltr" },
  {
    code: "crh-Cyrl",
    name: "Crimean Tatar (Cyrillic)",
    localName: "Къырымтатарджа (Кирилл)",
    direction: "ltr",
  },
  {
    code: "crh-Latn",
    name: "Crimean Tatar (Latin)",
    localName: "Qırımtatarca (Latin)",
    direction: "ltr",
  },
  { code: "hr", name: "Croatian", localName: "Hrvatski", direction: "ltr" },
  { code: "cs", name: "Czech", localName: "Čeština", direction: "ltr" },
  { code: "da", name: "Danish", localName: "Dansk", direction: "ltr" },
  { code: "prs", name: "Dari", localName: "دری", direction: "rtl" },
  { code: "dv", name: "Dhivehi", localName: "ދިވެހި", direction: "rtl" },
  { code: "din", name: "Dinka", localName: "Thuɔŋjäŋ", direction: "ltr" },
  { code: "doi", name: "Dogri", localName: "डोगरी", direction: "ltr" },
  { code: "dop", name: "Dombe", direction: "ltr" },
  { code: "nl", name: "Dutch", localName: "Nederlands", direction: "ltr" },
  { code: "dyu", name: "Dyula", localName: "Julakan", direction: "ltr" },
  { code: "dz", name: "Dzongkha", localName: "རྫོང་ཁ", direction: "ltr" },
  { code: "en", name: "English", direction: "ltr" },
  { code: "eo", name: "Esperanto", direction: "ltr" },
  { code: "et", name: "Estonian", localName: "Eesti", direction: "ltr" },
  { code: "ee", name: "Ewe", localName: "Eʋegbe", direction: "ltr" },
  { code: "fo", name: "Faroese", localName: "Føroyskt", direction: "ltr" },
  { code: "fj", name: "Fijian", localName: "Vosa Vakaviti", direction: "ltr" },
  { code: "fil", name: "Filipino", localName: "Filipino", direction: "ltr" },
  { code: "fi", name: "Finnish", localName: "Suomi", direction: "ltr" },
  { code: "fon", name: "Fon", direction: "ltr" },
  { code: "fr", name: "French", localName: "Français", direction: "ltr" },
  {
    code: "fr-CA",
    name: "French (Canada)",
    localName: "Français Canadien",
    direction: "ltr",
  },
  { code: "fy", name: "Frisian", localName: "Frysk", direction: "ltr" },
  { code: "fur", name: "Friulian", localName: "Furlan", direction: "ltr" },
  { code: "ff", name: "Fulani", localName: "Fulfulde", direction: "ltr" },
  { code: "gaa", name: "Ga", direction: "ltr" },
  { code: "gl", name: "Galician", localName: "Galego", direction: "ltr" },
  { code: "ka", name: "Georgian", localName: "ქართული", direction: "ltr" },
  { code: "de", name: "German", localName: "Deutsch", direction: "ltr" },
  { code: "el", name: "Greek", localName: "Ελληνικά", direction: "ltr" },
  { code: "gn", name: "Guarani", localName: "Avañe'ẽ", direction: "ltr" },
  { code: "gu", name: "Gujarati", localName: "ગુજરાતી", direction: "ltr" },
  {
    code: "ht",
    name: "Haitian Creole",
    localName: "Kreyòl Ayisyen",
    direction: "ltr",
  },
  { code: "cnh", name: "Hakha Chin", localName: "Laiholh", direction: "ltr" },
  { code: "ha", name: "Hausa", localName: "Hausa", direction: "rtl" },
  {
    code: "haw",
    name: "Hawaiian",
    localName: "ʻŌlelo Hawaiʻi",
    direction: "ltr",
  },
  { code: "he", name: "Hebrew", localName: "עברית", direction: "rtl" },
  { code: "hil", name: "Hiligaynon", direction: "ltr" },
  { code: "hi", name: "Hindi", localName: "हिन्दी", direction: "ltr" },
  { code: "hmn", name: "Hmong", localName: "Hmoob", direction: "ltr" },
  { code: "hu", name: "Hungarian", localName: "Magyar", direction: "ltr" },
  { code: "hrx", name: "Hunsrik", direction: "ltr" },
  { code: "iba", name: "Iban", direction: "ltr" },
  { code: "is", name: "Icelandic", localName: "Íslenska", direction: "ltr" },
  { code: "ig", name: "Igbo", localName: "Igbo", direction: "ltr" },
  { code: "ilo", name: "Ilocano", localName: "Ilokano", direction: "ltr" },
  {
    code: "id",
    name: "Indonesian",
    localName: "Bahasa Indonesia",
    direction: "ltr",
  },
  { code: "iu-Latn", name: "Inuktut (Latin)", direction: "ltr" },
  {
    code: "iu",
    name: "Inuktut (Syllabics)",
    localName: "ᐃᓄᒃᑎᑐᑦ",
    direction: "ltr",
  },
  { code: "ga", name: "Irish", localName: "Gaeilge", direction: "ltr" },
  { code: "it", name: "Italian", localName: "Italiano", direction: "ltr" },
  { code: "jam", name: "Jamaican Patois", direction: "ltr" },
  { code: "ja", name: "Japanese", localName: "日本語", direction: "ltr" },
  { code: "jv", name: "Javanese", localName: "Basa Jawa", direction: "ltr" },
  { code: "kac", name: "Jingpo", direction: "ltr" },
  {
    code: "kl",
    name: "Kalaallisut",
    localName: "Kalaallisut",
    direction: "ltr",
  },
  { code: "kn", name: "Kannada", localName: "ಕನ್ನಡ", direction: "ltr" },
  { code: "kr", name: "Kanuri", direction: "ltr" },
  { code: "pam", name: "Kapampangan", direction: "ltr" },
  { code: "kk", name: "Kazakh", localName: "Қазақша", direction: "ltr" },
  { code: "kha", name: "Khasi", direction: "ltr" },
  { code: "km", name: "Khmer", localName: "ភាសាខ្មែរ", direction: "ltr" },
  { code: "cgg", name: "Kiga", direction: "ltr" },
  { code: "kg", name: "Kikongo", localName: "Kikongo", direction: "ltr" },
  {
    code: "rw",
    name: "Kinyarwanda",
    localName: "Ikinyarwanda",
    direction: "ltr",
  },
  { code: "mkw", name: "Kituba", direction: "ltr" },
  { code: "kok", name: "Kokborok", direction: "ltr" },
  { code: "kv", name: "Komi", localName: "Коми", direction: "ltr" },
  { code: "ko", name: "Korean", localName: "한국어", direction: "ltr" },
  { code: "kri", name: "Krio", direction: "ltr" },
  {
    code: "ku",
    name: "Kurdish (Kurmanji)",
    localName: "Kurmancî",
    direction: "rtl",
  },
  {
    code: "ckb",
    name: "Kurdish (Sorani)",
    localName: "سۆرانی",
    direction: "rtl",
  },
  { code: "ky", name: "Kyrgyz", localName: "Кыргызча", direction: "ltr" },
  { code: "lo", name: "Lao", localName: "ລາວ", direction: "ltr" },
  { code: "ltg", name: "Latgalian", localName: "Latgaļu", direction: "ltr" },
  { code: "la", name: "Latin", localName: "Latina", direction: "ltr" },
  { code: "lv", name: "Latvian", localName: "Latviešu", direction: "ltr" },
  { code: "lij", name: "Ligurian", localName: "Ligure", direction: "ltr" },
  { code: "li", name: "Limburgish", localName: "Limburgs", direction: "ltr" },
  { code: "ln", name: "Lingala", localName: "Lingála", direction: "ltr" },
  { code: "lt", name: "Lithuanian", localName: "Lietuvių", direction: "ltr" },
  { code: "lmo", name: "Lombard", localName: "Lombard", direction: "ltr" },
  { code: "lg", name: "Luganda", localName: "Luganda", direction: "ltr" },
  { code: "luo", name: "Luo", direction: "ltr" },
  {
    code: "lb",
    name: "Luxembourgish",
    localName: "Lëtzebuergesch",
    direction: "ltr",
  },
  { code: "mk", name: "Macedonian", localName: "Македонски", direction: "ltr" },
  { code: "mad", name: "Madurese", direction: "ltr" },
  { code: "mai", name: "Maithili", localName: "मैथिली", direction: "ltr" },
  { code: "mak", name: "Makassar", direction: "ltr" },
  { code: "mg", name: "Malagasy", localName: "Malagasy", direction: "ltr" },
  { code: "ms", name: "Malay", localName: "Bahasa Melayu", direction: "ltr" },
  {
    code: "ms-Arab",
    name: "Malay (Jawi)",
    localName: "بهاس ملايو",
    direction: "rtl",
  },
  { code: "ml", name: "Malayalam", localName: "മലയാളം", direction: "ltr" },
  { code: "mt", name: "Maltese", localName: "Malti", direction: "ltr" },
  { code: "mam", name: "Mam", direction: "ltr" },
  { code: "gv", name: "Manx", localName: "Gaelg", direction: "ltr" },
  { code: "mi", name: "Maori", localName: "Māori", direction: "ltr" },
  { code: "mr", name: "Marathi", localName: "मराठी", direction: "ltr" },
  {
    code: "mh",
    name: "Marshallese",
    localName: "Kajin M̧ajeļ",
    direction: "ltr",
  },
  { code: "mwr", name: "Marwadi", direction: "ltr" },
  {
    code: "mfe",
    name: "Mauritian Creole",
    localName: "Kreol Morisien",
    direction: "ltr",
  },
  {
    code: "mhr",
    name: "Meadow Mari",
    localName: "Олык Марий",
    direction: "ltr",
  },
  {
    code: "mni",
    name: "Meiteilon (Manipuri)",
    localName: "ꯃꯤꯇꯩꯂꯣꯟ",
    direction: "ltr",
  },
  { code: "min", name: "Minang", direction: "ltr" },
  { code: "lus", name: "Mizo", localName: "Mizo ṭawng", direction: "ltr" },
  { code: "mn", name: "Mongolian", localName: "Монгол", direction: "ltr" },
  {
    code: "my",
    name: "Myanmar (Burmese)",
    localName: "မြန်မာစာ",
    direction: "ltr",
  },
  {
    code: "nhe",
    name: "Nahuatl (Eastern Huasteca)",
    localName: "Nāhuatlahtōlli",
    direction: "ltr",
  },
  { code: "ndc", name: "Ndau", direction: "ltr" },
  {
    code: "nr",
    name: "Ndebele (South)",
    localName: "isiNdebele",
    direction: "ltr",
  },
  {
    code: "new",
    name: "Nepalbhasa (Newari)",
    localName: "नेपाल भाषा",
    direction: "ltr",
  },
  { code: "ne", name: "Nepali", localName: "नेपाली", direction: "ltr" },
  { code: "nqo", name: "NKo", localName: "ߒߞߏ", direction: "rtl" },
  { code: "no", name: "Norwegian", localName: "Norsk", direction: "ltr" },
  { code: "nus", name: "Nuer", localName: "Thok Nath", direction: "ltr" },
  { code: "oc", name: "Occitan", localName: "Occitan", direction: "ltr" },
  { code: "or", name: "Odia (Oriya)", localName: "ଓଡ଼ିଆ", direction: "ltr" },
  { code: "om", name: "Oromo", localName: "Afaan Oromoo", direction: "ltr" },
  { code: "os", name: "Ossetian", localName: "Ирон", direction: "ltr" },
  { code: "pag", name: "Pangasinan", direction: "ltr" },
  { code: "pap", name: "Papiamento", direction: "ltr" },
  { code: "ps", name: "Pashto", localName: "پښتو", direction: "rtl" },
  { code: "fa", name: "Persian", localName: "فارسی", direction: "rtl" },
  { code: "pl", name: "Polish", localName: "Polski", direction: "ltr" },
  {
    code: "pt-BR",
    name: "Portuguese (Brazil)",
    localName: "Português Brasileiro",
    direction: "ltr",
  },
  {
    code: "pt-PT",
    name: "Portuguese (Portugal)",
    localName: "Português Europeu",
    direction: "ltr",
  },
  {
    code: "pa",
    name: "Punjabi (Gurmukhi)",
    localName: "ਪੰਜਾਬੀ",
    direction: "ltr",
  },
  {
    code: "pa-Arab",
    name: "Punjabi (Shahmukhi)",
    localName: "پنجابی",
    direction: "rtl",
  },
  { code: "qu", name: "Quechua", localName: "Runa Simi", direction: "ltr" },
  { code: "kek", name: "Qʼeqchiʼ", direction: "ltr" },
  { code: "rom", name: "Romani", localName: "Romani", direction: "ltr" },
  { code: "ro", name: "Romanian", localName: "Română", direction: "ltr" },
  { code: "rn", name: "Rundi", localName: "Kirundi", direction: "ltr" },
  { code: "ru", name: "Russian", localName: "Русский", direction: "ltr" },
  {
    code: "se",
    name: "Sami (North)",
    localName: "Davvisámegiella",
    direction: "ltr",
  },
  { code: "sm", name: "Samoan", localName: "Gagana Samoa", direction: "ltr" },
  { code: "sg", name: "Sango", localName: "Sängö", direction: "ltr" },
  { code: "sa", name: "Sanskrit", localName: "संस्कृतम्", direction: "ltr" },
  {
    code: "sat",
    name: "Santali (Latin)",
    localName: "Santali",
    direction: "ltr",
  },
  {
    code: "sat-Olck",
    name: "Santali (Ol Chiki)",
    localName: "ᱥᱟᱱᱛᱟᱲᱤ",
    direction: "ltr",
  },
  { code: "gd", name: "Scots Gaelic", localName: "Gàidhlig", direction: "ltr" },
  {
    code: "nso",
    name: "Sepedi",
    localName: "Sesotho sa Leboa",
    direction: "ltr",
  },
  { code: "sr", name: "Serbian", localName: "Српски", direction: "ltr" },
  { code: "st", name: "Sesotho", localName: "Sesotho", direction: "ltr" },
  {
    code: "crs",
    name: "Seychellois Creole",
    localName: "Kreol Seselwa",
    direction: "ltr",
  },
  { code: "shn", name: "Shan", localName: "ၽႃႇသႃႇတႆး", direction: "ltr" },
  { code: "sn", name: "Shona", localName: "chiShona", direction: "ltr" },
  { code: "scn", name: "Sicilian", localName: "Sicilianu", direction: "ltr" },
  {
    code: "szl",
    name: "Silesian",
    localName: "Ślōnskŏ gŏdka",
    direction: "ltr",
  },
  { code: "sd", name: "Sindhi", localName: "سنڌي", direction: "rtl" },
  { code: "si", name: "Sinhala", localName: "සිංහල", direction: "ltr" },
  { code: "sk", name: "Slovak", localName: "Slovenčina", direction: "ltr" },
  { code: "sl", name: "Slovenian", localName: "Slovenščina", direction: "ltr" },
  { code: "so", name: "Somali", localName: "Soomaali", direction: "ltr" },
  { code: "es", name: "Spanish", localName: "Español", direction: "ltr" },
  { code: "su", name: "Sundanese", localName: "Basa Sunda", direction: "ltr" },
  { code: "sus", name: "Susu", direction: "ltr" },
  { code: "sw", name: "Swahili", localName: "Kiswahili", direction: "ltr" },
  { code: "ss", name: "Swati", localName: "SiSwati", direction: "ltr" },
  { code: "sv", name: "Swedish", localName: "Svenska", direction: "ltr" },
  { code: "ty", name: "Tahitian", localName: "Reo Tahiti", direction: "ltr" },
  { code: "tg", name: "Tajik", localName: "Тоҷикӣ", direction: "ltr" },
  { code: "zgh", name: "Tamazight", localName: "ⵜⴰⵎⴰⵣⵉⵖⵜ", direction: "ltr" },
  {
    code: "tzm",
    name: "Tamazight (Tifinagh)",
    localName: "ⵜⴰⵎⴰⵣⵉⵖⵜ",
    direction: "ltr",
  },
  { code: "ta", name: "Tamil", localName: "தமிழ்", direction: "ltr" },
  { code: "tt", name: "Tatar", localName: "Татарча", direction: "ltr" },
  { code: "te", name: "Telugu", localName: "తెలుగు", direction: "ltr" },
  { code: "tet", name: "Tetum", localName: "Tetun", direction: "ltr" },
  { code: "th", name: "Thai", localName: "ไทย", direction: "ltr" },
  { code: "bo", name: "Tibetan", localName: "བོད་སྐད་", direction: "ltr" },
  { code: "ti", name: "Tigrinya", localName: "ትግርኛ", direction: "ltr" },
  { code: "tiv", name: "Tiv", direction: "ltr" },
  { code: "tpi", name: "Tok Pisin", direction: "ltr" },
  { code: "to", name: "Tongan", localName: "Lea faka-Tonga", direction: "ltr" },
  { code: "lua", name: "Tshiluba", localName: "Tshiluba", direction: "ltr" },
  { code: "ts", name: "Tsonga", localName: "Xitsonga", direction: "ltr" },
  { code: "tn", name: "Tswana", localName: "Setswana", direction: "ltr" },
  { code: "tcy", name: "Tulu", localName: "ತುಳು", direction: "ltr" },
  { code: "tum", name: "Tumbuka", direction: "ltr" },
  { code: "tr", name: "Turkish", localName: "Türkçe", direction: "ltr" },
  { code: "tk", name: "Turkmen", localName: "Türkmençe", direction: "ltr" },
  { code: "tyv", name: "Tuvan", localName: "Тыва дыл", direction: "ltr" },
  { code: "tw", name: "Twi", localName: "Twi", direction: "ltr" },
  { code: "udm", name: "Udmurt", localName: "Удмурт", direction: "ltr" },
  { code: "uk", name: "Ukrainian", localName: "Українська", direction: "ltr" },
  { code: "ur", name: "Urdu", localName: "اردو", direction: "rtl" },
  { code: "ug", name: "Uyghur", localName: "ئۇيغۇرچە", direction: "rtl" },
  { code: "uz", name: "Uzbek", localName: "Oʻzbekcha", direction: "ltr" },
  { code: "ve", name: "Venda", localName: "Tshivenḓa", direction: "ltr" },
  { code: "vec", name: "Venetian", localName: "Vèneto", direction: "ltr" },
  { code: "vi", name: "Vietnamese", localName: "Tiếng Việt", direction: "ltr" },
  { code: "war", name: "Waray", localName: "Winaray", direction: "ltr" },
  { code: "cy", name: "Welsh", localName: "Cymraeg", direction: "ltr" },
  { code: "wo", name: "Wolof", localName: "Wolof", direction: "ltr" },
  { code: "xh", name: "Xhosa", localName: "isiXhosa", direction: "ltr" },
  { code: "sah", name: "Yakut", localName: "Саха тыла", direction: "ltr" },
  { code: "yi", name: "Yiddish", localName: "ייִדיש", direction: "rtl" },
  { code: "yo", name: "Yoruba", localName: "Yorùbá", direction: "ltr" },
  {
    code: "yua",
    name: "Yucatec Maya",
    localName: "Màaya t'àan",
    direction: "ltr",
  },
  { code: "zap", name: "Zapotec", direction: "ltr" },
  { code: "zu", name: "Zulu", localName: "isiZulu", direction: "ltr" },
];
